version: "3"

services:

    nginx:
        container_name: nginx
        build: ./nginx
        image: test/nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./log:/var/log/nginx
        depends_on:
            - backend
            - frontend

    backend:
        container_name: backend
        build: ./backend
        image: test/backend
        restart: always
        ports:
            - "8000:8000"
        command: uwsgi --ini uwsgi.ini
        volumes:
            - ./backend:/backend
            - ./log:/var/log/uwsgi

    frontend:
        container_name: frontend
        build: ./frontend
        image: test/frontend
        restart: always
        expose:
            - 3000
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - /frontend/node_modules
            - ./frontend:/frontend
        stdin_open: true
        tty: true

    db:
        container_name: db
        image: mysql:latest
        restart: always
        ports:
            - "3306:3306"
        env_file: .env
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --lower_case_table_names=1
        volumes:
            - ./db/data:/var/lib/mysql
